### PR TITLE
Add revert/require error messages to dnssec.sol

### PR DESCRIPTION
**Pull request by Arachnid**

### CODE REVIEW

**Comment by decanus** [comment]
@Arachnid I'd like to have some kind of error message standard. ```File:Line Message```, this might help with displaying in the frontend and logging. It might be good to see if there is some EIP standard for this already.

**Comment by Arachnid** [comment]
@decanus There's not, AFAIK. I'd happily make them into error codes instead of descriptive messages; it'd save on gas.

**Comment by makoto** [comment]
You may want to add comment to line 235 `revert()` to something like `revert('End of deleteRRSet')`

**Comment by makoto** [comment]
Can we somehow differentiate the error messages of the two below so that we know which line emitted the error?
```
392:        require(signerNameLength <= name.length, "Signer name must be a parent of RRSet");
393:        require(data.equals(RRSIG_SIGNER_NAME, name, name.length - signerNameLength, signerNameLength), "Signer name must be a parent of RRSet");
```

**Comment by makoto** [comment]
Are you also going to add message on `BytesUtils.sol` and `Owned.sol` or is it going to be handled by a separate PR?

**Comment by makoto** [comment]
I am closing out of date PR

**Pull request closed without merging**
