### PR TITLE
Fix odd-length key tag calculation

### PR DESCRIPTION
**Pull request by jablko**
I'd like to be able to wrap lines automatically ... Would you consider accepting a pull request that ran the `prettier` tool? I split it into two commits: In the first I just ran the code formatter. All actual changes are in the second commit.

### CODE REVIEW

**Comment by Arachnid** [comment]
Can you change the title of this PR to reflect the changes it makes?

**Comment by jablko** [comment]
> Can you change the title of this PR to reflect the changes it makes?

Yes, I think this is better? `computeKeytag()` previously failed if `data.length` was odd.

**Comment by Arachnid** [comment]
Can you move the formatting changes into their own PR, then? It's hard to review something with both formatting changes and substantive ones.

**Comment by jablko** [comment]
> Can you move the formatting changes into their own PR, then? It's hard to review something with both formatting changes and substantive ones.

Sure thing: I opened #64 for the formatting changes. Here are [the substantive changes](https://github.com/ensdomains/dnssec-oracle/pull/63/commits/8584f5dd808bb1751384605fa55fbc2d12adaab8).

**Comment by Arachnid** [comment]
Thanks for all your contributions! Why the sudden interest in ENS and the DNSSEC oracle?

**Pull request merged**
