### PR TITLE
Reject expired proofs

### PR DESCRIPTION
**Pull request by jablko**

### CODE REVIEW

**Comment by jablko** [comment]
The way I see it a signed RRset is valid only while it has a valid RRSIG, so you can't continue to use a DNSKEY after the RRSIG that signed it expires. Unless you get a new, valid RRSIG.

> It's possible for a record to have a TTL that's longer than the remaining time before the record expires, and that's okay - you validate the signature when you receive it, then store the record as valid until its TTL expires.

You can store it, you just can't store it as valid.

The [relevant section of the RFC](https://tools.ietf.org/html/rfc4033#section-8.1) says:

> TTL values cannot extend the validity period of signed RRsets in a resolver's cache, but the resolver may use the time remaining before expiration of the signature validity period of a signed RRset as an upper bound for the TTL of the signed RRset and its associated RRSIG RR in the resolver's cache.

**Comment by Arachnid** [comment]
The section you quote seems to say it's okay to do what we're doing right now. It says TTLs can't *extend* the signature's validity period, not that they can't *exceed* the validity period.

**Comment by jablko** [comment]
Sure, but since it doesn't extend, when it does exceed, you can't use it to validate additional RRsets.

Validation requires a valid antecedent:
> The validator first checks the RRSIG RR to verify that it covers the RRset, has a valid time interval, and identifies a valid DNSKEY RR.
> [RFC 4035 Section 5.3 Authenticating an RRset with an RRSIG RR](https://tools.ietf.org/html/rfc4035#section-5.3)

and validity is constrained by the signature validity period:
> Signatures in DNSSEC have an expiration date after which the signature is marked as invalid and the signed data is to be considered Bogus.
> [RFC 6781 Section 4.4 Time in DNSSEC](https://tools.ietf.org/html/rfc6781#section-4.4)

What if you validate before the end of the signature validity period, does the RRset stay valid beyond it? To me, "TTL values cannot extend [but can exceed] the validity period of signed RRsets in a resolver's cache," says no: Validity and TTL values are independent. The validity of an authentication chain is intrinsic, it doesn't depend on the times at which you previously validate component proofs.

**Comment by Arachnid** [comment]
Sorry, I really don't understand your argument. The RFC, and the sections you're quoting clearly seem to say the following:

 - A record's TTL can be constrained to the validity period of the signing RRSIG, but doesn't have to be (so, a record can remain valid even after the RRSIG's validity period has expired).
 - The validity period has to be checked at the time that the RRSIG is being validated.
 - Once you've checked the validity of a record and its RRSIG, you can rely on it until it expires.

All of these seem to me to mean that what we're doing now is correct: The validity period applies to the signature, not the records it signs, and once we've validated it, we no longer need the signature, or need to care about how long it remains valid for.

There are good reasons to allow this, too: Most users don't have direct control over the key and signature rotation for their zone, but want to be able to set very long TTLs for caching. And keys are rotated regularly to reduce the risk of a key being compromised while it's still live - but with correct key rotation, it's fine to have a record with an extended TTL.

**Comment by jablko** [comment]
Sorry, I should have said: The TTL can exceed the validity period but when it does the signed RRset (like the RRSIG) isn't valid, even if it was validated in the past, and can't be used to validate additional RRsets. When that happens you're obliged to get a fresh, valid RRSIG.

What the RFC is referring to is (optionally) caching invalid data: [RFC 4035 Section 4.7 Caching BAD Data](https://tools.ietf.org/html/rfc4035#section-4.7)

The CD query bit can be set to cause the resolver to skip validation and return whatever it gets from upstream. The originating resolver takes responsibility for it. You can optionally cache it, and instead of going upstream, you can optionally return fresh, cached but signature expired (hence invalid) data. [RFC 4035 Section 3.2.2 The CD Bit](https://tools.ietf.org/html/rfc4035#section-3.2.2)

The examples given of reasons for setting the CD bit are in cases of persistent validation failures due to "failure to re-sign a zone, clock skew, and so forth."

It's not saying that a record can remain valid after the RRSIG's validity period has expired, it's making the opposite point: That (optionally) caching invalid, signature expired data "cannot extend the validity period of signed RRsets in a resolver's cache."

In that case where you can't choose your validity period and you set a very long TTL, I think security-oblivious caches normally respect it, and security-aware caches might or might not (optionally) when the CD bit is set. Otherwise it will be cached until the (absolute) signature expiration time, which is why it's not recommended:
> If the TTL duration was similar to that of the signature validity period, then all RRsets fetched during the validity period would be cached until the signature expiration time. Section 8.1 of RFC 4033 suggests that "the resolver may use the time remaining before expiration of the signature validity period of a signed RRset as an upper bound for the TTL".  As a result, the query load on authoritative servers would peak at the signature expiration time, as this is also the time at which records simultaneously expire from caches.
> [RFC 6781 Section 4.4.1 Time Considerations](https://tools.ietf.org/html/rfc6781#section-4.4.1)

**Comment by Arachnid** [comment]
> Sorry, I should have said: The TTL can exceed the validity period but when it does the signed RRset (like the RRSIG) isn't valid, even if it was validated in the past, and can't be used to validate additional RRsets. When that happens you're obliged to get a fresh, valid RRSIG.

I don't think that's the case. Where are you reading that?

You said earlier:

> Validation requires a valid antecedent:
> 
> > The validator first checks the RRSIG RR to verify that it covers the RRset, has a valid time interval, and identifies a valid DNSKEY RR.
> > RFC 4035 Section 5.3 Authenticating an RRset with an RRSIG RR

But this happens at the time the RRSIG is validated - eg, when it's first received and added to the DB.

>
> and validity is constrained by the signature validity period:
> 
> > Signatures in DNSSEC have an expiration date after which the signature is marked as invalid and the signed data is to be considered Bogus.
> > RFC 6781 Section 4.4 Time in DNSSEC

And this refers to when the signature expires, not when the record covered by the signature expires.

**Comment by jablko** [comment]
> But this happens at the time the RRSIG is validated - eg, when it's first received and added to the DB.

For sure, but it also happens when additional RRsets are validated. What I meant was, say you validate the `xyz.` DNSKEY. Time goes by and you want to validate the `backtothefuture.xyz.` DS record. I think we agree, the RFC says you need a valid DNSKEY. If you're before the DNSKEY's signature expiration then the signature is valid, the DNSKEY is valid, you can use it. I'm saying that after the DNSKEY's signature expiration the signature is invalid, the DNSKEY is invalid, you can't use it because: "TTL values cannot extend the validity period of signed RRsets [the DNSKEY] in a resolver's cache." You need a new, valid DNSKEY.

> And this refers to when the signature expires, not when the record covered by the signature expires.

"the signed data is to be considered Bogus" is the record covered by the signature, so after the signature expires the record is invalid. Critically, it's not saying it matters whether you validated the record before the signature expired ...

Rereading [RFC 4033 Section 8.1 TTL Values vs. RRSIG Validity Period](https://tools.ietf.org/html/rfc4033#section-8.1), we agree it says signatures are invalid after they expire, and the TTL of the RRset can be limited to the signature expiration or it can be the full TTL, at the resolver's discretion. I'm saying that's for caching invalid data, the CD query bit, and doesn't make the RRset valid for the full TTL. We agree the RRset (like the signature) is invalid if you validate after the signature expiration. You're saying if you validate before the signature expiration, the RRset can be valid for the full TTL, at the resolver's discretion. I think "TTL values cannot extend the validity period of signed RRsets in a resolver's cache" is talking about the RRset (e.g. DNSKEY) not just the RRSIG, and "validity period of signed RRsets" means the period that the RRset is valid, not just the signature.

Otherwise it's saying "the validity period of the RRset" is not the same thing as the validity period of the signature (or not the period that the RRset is valid) and the validity period of the RRset can exceed that of the signature (optionally) if the RRset is validated before the signature expiration. That's not what I get from reading the RFC. For example:
> The RRSIG records that accompany zone data have defined inception and expiration times that establish a validity period for the signatures and the zone data the signatures cover.
> [RFC 4033 Section 8 Zone Considerations](https://tools.ietf.org/html/rfc4033#section-8)

Current oracle behavior is if you validate an authentication chain and one of the signatures is expired, the chain is invalid. But if in the past you validated a component of the chain before it expired, the oracle considers if valid for its TTL, which makes the same, invalid authentication chain valid. I think this is exactly the point the RFC is making when it says "TTL values cannot extend the validity period of signed RRsets in a resolver's cache." It would be like a security-aware resolver returning a result whose authentication chain you couldn't validate, because the resolver previously validated a component of the chain, no?

**Comment by Arachnid** [comment]
I asked the DNSOP WG about this, and they referred me to RFC4035, section 5.3.3:

>   If the resolver accepts the RRset as authentic, the validator MUST
>   set the TTL of the RRSIG RR and each RR in the authenticated RRset to
>   a value no greater than the minimum of:
>
>   o  the RRset's TTL as received in the response;
>
>   o  the RRSIG RR's TTL as received in the response;
>
>   o  the value in the RRSIG RR's Original TTL field; and
>
>   o  the difference of the RRSIG RR's Signature Expiration time and the
>      current time.

If you'd like to update your PR to reflect this, I'll be happy to accept it. We shouldn't need to record the 'expiration' field, though - just the insertion time and the TTL, or alternately, just the expiration field but not those two fields.

**Comment by jablko** [comment]
:+1: Sounds good, I'll update it.

**Comment by jablko** [comment]
Done. I updated it to record just the expiration field, and am closing this PR in favor of #68.

**Pull request closed without merging**
