### PR TITLE
[DO NOT MERGE] Potential Delete record bug on NSEC3

### PR DESCRIPTION
**Pull request by makoto**
# The problem diagnosys of why deleteRRSet is not working.

## High level summary.

Looks like deleteRRSet is failing in the following order.

`deleteRRSet` -> `validateSignedSet` -> `validateRRs` -> `require(name.equals(0, data, iter.offset, name.length), 'validateRRs3');`

The line checks if the name given at the first paramern (`_ens.matoken.xyz`) matches with the name contained in NSEC3 entry and RRSIG entry.
Becuase NSEC3 hashes these entries, it will be different from subdomain seems different,

```
    //   r8u7h0kpjdkv8tlp07e79fvascqsdbl2.matoken.xyz	300	NSEC3	IN	{"algorithm":1,"flags":0,"iterations":1,"salt":{"type":"Buffer","data":[238,133,139,204,143,18,43,84]},"nextDomain":{"type":"Buffer","data":[48,231,172,215,13,64,134,128,62,98,41,105,128,99,66,59,88,69,121,162]},"rrtypes":["NS","SOA","RRSIG","DNSKEY","NSEC3PARAM","CDS"]}
    //   63jqplod82380fj255ko0oq27dc4aud2.matoken.xyz	300	NSEC3	IN	{"algorithm":1,"flags":0,"iterations":1,"salt":{"type":"Buffer","data":[238,133,139,204,143,18,43,84]},"nextDomain":{"type":"Buffer","data":[218,60,120,130,153,155,105,244,118,185,1,220,116,191,234,227,53,198,174,162]},"rrtypes":["CNAME","RRSIG"]}
    //   r8u7h0kpjdkv8tlp07e79fvascqsdbl2.matoken.xyz	300	RRSIG	IN	NSEC3	8	3	300	1570289035	1568388235	62926	matoken.xyz	c5n+Vxl1DfLhQf/2z0f+7poSvFZwxy5zrrkEJv5j9cBH3RYBS5WIcx5HRQca/0WWvAcDicyEM3RpVaratjhZUCAz/kfvoB28UFHMVrGan8dgiA8r30HDTDP56tD1XCgpqO0sqx+c+g/HeirYJ2gDEtLzNsja4dcXqWDoRkn5ScU=
    // ["_ens.matoken.xyz","0x003208030000012c5d98b58b5d7bb48bf5ce076d61746f6b656e0378797a002036336a71706c6f643832333830666a3235356b6f306f71323764633461756432076d61746f6b656e0378797a00003200010000012c002a0100000108ee858bcc8f122b5414da3c7882999b69f476b901dc74bfeae335c6aea20006040000000002207238753768306b706a646b7638746c7030376537396676617363717364626c32076d61746f6b656e0378797a00003200010000012c002c0100000108ee858bcc8f122b541430e7acd70d4086803e6229698063423b584579a200082200000000029010","0x7399fe5719750df2e141fff6cf47feee9a12bc5670c72e73aeb90426fe63f5c047dd16014b9588731e4745071aff4596bc070389cc8433746955aadab63859502033fe47efa01dbc5051cc56b19a9fc760880f2bdf41c34c33f9ead0f55c2829a8ed2cab1f9cfa0fc77a2ad827680312d2f336c8dae1d717a960e84649f949c5"],]
```

I tried passing `r8u....matoken.xyz` instead but still failed as it was checking names against both `r8u....matoken` and `63j....matoken`

### Upgrade ganache to the latest 

```
npm uninstall
npm install -g ganache-cli
```

### Startup ganache

```
ganache-cli
```

### Get the code

```
git clone https://github.com/ensdomains/dnssec-oracle
git checkout cdbdd91c380a2a9c5c0cd7bc525738254adfe53a 
cd dnssec-oracle
npm install
```

#### Compile and run the test

```
rm -rf build
npx truffle compile
npx truffle test
```

Output
```
  1 passing (7s)
  1 failing

  1) Contract: DNSSEC
       deleteRRSet:
     Error: Returned error: VM Exception while processing transaction: revert validateRRs3 -- Reason given: validateRRs3.
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:6:1)
      at TruffleContract.deleteRRSet (node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:157:1)
      at Context.<anonymous> (test/TestDNSSEC.js:1259:33)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Check the last log of ganache to grab the failing transaction

```
eth_sendTransaction

  Transaction: 0x985ece512946535e51e18ff14a87f429f80f353eefd8e0723becedb4cfeeabc7
  Gas usage: 92893
  Block Number: 73
  Block Time: Tue Sep 17 2019 17:43:59 GMT+0100 (British Summer Time)
  Runtime Error: revert
  Revert reason: validateRRs3
```

### Invoke debugger

```
$npx truffle debug 0x985ece512946535e51e18ff14a87f429f80f353eefd8e0723becedb4cfeeabc7
Starting Truffle Debugger...
✔ Compiling your contracts...
✔ Gathering information about your project and the transaction...

Addresses called: (not created)
 0x55d5ecc801BeAeC195E9fCC2f065C0907445A984 - DNSSECImpl

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(;) step instruction (include number to step multiple), (p) print instruction
(h) print this help, (q) quit, (r) reset
(t) load new transaction, (T) unload transaction
(b) add breakpoint, (B) remove breakpoint, (c) continue until breakpoint
(+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
(?) list existing watch expressions and breakpoints
(v) print variables and values, (:) evaluate expression - see `v`


DNSSECImpl.sol:

15:  * TODO: Support for NSEC3 records
16:  */
17: contract DNSSECImpl is DNSSEC, Owned {
```

##### Set watcher and beakpoint

```
debug(development:0x985ece51...)> +:namebody
undefined
debug(development:0x985ece51...)> +:databody
undefined
debug(development:0x985ece51...)> b 378
Breakpoint added at line 378.

debug(development:0x985ece51...)> c
⠋ Stepping...

```

+:namebody
+:databody

##### Set breakpoint and go to the poiint

```
debug(development:0x985ece51...)> c

DNSSECImpl.sol:

376:                 bytes memory namebody = name.substring(0, name.length);
377:                 bytes memory databody = data.substring(iter.offset, name.length);
378:                 require(name.equals(0, data, iter.offset, name.length), 'validateRRs3');
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  

:namebody
  '0x2036336a71706c6f643832333830666a3235356b6f306f71323764633461756432076d61746f6b656e0378797a00'

:databody
  '0x207238753768306b706a646b7638746c7030376537396676617363717364626c32076d61746f6b656e0378797a00'

debug(development:0x985ece51...)> 
```

When you set an first argument `name` as `0x2036` then body shows `0x207`.
If you replace the name to `0x207`, then body shows `0x2036'.
These indicates that the line 378 are checking names for both RRSIG and NSEC3 names against `name` arugment and it fails on either side.

### CODE REVIEW

**Comment by Arachnid** [comment]
Looking at this in detail at long last.

> Looks like deleteRRSet is failing in the following order.
> 
> deleteRRSet -> validateSignedSet -> validateRRs -> require(name.equals(0, data, iter.offset, name.length), 'validateRRs3');
> 
> The line checks if the name given at the first paramern (_ens.matoken.xyz) matches with the name contained in NSEC3 entry and RRSIG entry.

The code there is checking that all the records in the signed RRSet are for the same name. Your RRSet contains records from two different names, `63jqplod82380fj255ko0oq27dc4aud2.matoken.xyz` and `r8u7h0kpjdkv8tlp07e79fvascqsdbl2.matoken.xyz.`, so the test fails.

Do you recall why your signed RRSET included records from multiple domains? This shouldn't be possible if it was generated by a compliant DNS implementation, and only one NSEC record should be required to prove nonexistence of a name.

**Comment by makoto** [comment]
I constructed data from https://dnssec.ens.domains.

`makoto.xyz` now correctly shows NSEC3 data.

Screenshot 2020-10-08 at 17 07 30

      nsec3 = "0x003208030000012c5f9adffa5f7ddefac9b4076d61746f6b656e0378797a002036336a71706c6f643832333830666a3235356b6f306f71323764633461756432076d61746f6b656e0378797a00003200010000012c002a0100000108ee858bcc8f122b5414da3c7882999b69f476b901dc74bfeae335c6aea200060400000000022036336a71706c6f643832333830666a3235356b6f306f71323764633461756432076d61746f6b656e0378797a00003200010000012c002a0100000108ee858bcc8f122b5414da3c7882999b69f476b901dc74bfeae335c6aea20006040000000002207238753768306b706a646b7638746c7030376537396676617363717364626c32076d61746f6b656e0378797a00003200010000012c002c0100000108ee858bcc8f122b541430e7acd70d4086803e6229698063423b584579a200082200000000029010"
      sig = "0x1b07988f386bc96c2f72ecdc743971d968ad1f7628d21fd7147abe741dd2129cf1e5652068ee0795f0b802ac0ddac24408ba100e4ddbd914349865bf1c671934a2dd152a6f6cdbf547056c49f6e537f36f35679cf5086e3c96fbcf103decb00214449fb34e84e1a8ceb2ef9e639488d8c480dec9deb18ec4bd13e9e4c1a44aa6"

As you mentioned, I do create signature using all rrset [here](https://github.com/ensdomains/dnsprovejs/blob/master/lib/dns/result.js#L53) which I use to construct all proofs to submit.

I made [this modification ](https://github.com/ensdomains/dnsprovejs/compare/delete-nsec3?expand=1) which only uses the first rrset for nsec/nsec3 which generated the following but still failing.

      nsec3 = "0x003208030000012c5f9adffa5f7ddefac9b4076d61746f6b656e0378797a00207238753768306b706a646b7638746c7030376537396676617363717364626c32076d61746f6b656e0378797a00003200010000012c002c0100000108ee858bcc8f122b541430e7acd70d4086803e6229698063423b584579a200082200000000029010"
      sig = "0x1b07988f386bc96c2f72ecdc743971d968ad1f7628d21fd7147abe741dd2129cf1e5652068ee0795f0b802ac0ddac24408ba100e4ddbd914349865bf1c671934a2dd152a6f6cdbf547056c49f6e537f36f35679cf5086e3c96fbcf103decb00214449fb34e84e1a8ceb2ef9e639488d8c480dec9deb18ec4bd13e9e4c1a44aa6"

**Comment by makoto** [comment]
So I made the following change and the test to delete `_ens.matoken.xyz` in TestDNSSEC.js is working (test name `deleteRRSet`).

1. pack data only using the 2nd rrset https://github.com/ensdomains/dnsprovejs/compare/delete-nsec3
2. copy&paste the nsec and sig derived from the change https://github.com/ensdomains/dnssec-oracle/pull/73/commits/725d55d9a796ce393cafd7c0d91a76bed3bd9038

Now when I try to delete record of `_ens.matoken.xyz` using the code from `ens-app`, the transaction fails. https://goerli.etherscan.io/tx/0xd87dc01e4ed5add82cd242cac10b71a6d8fc419f3d1d3e1e46c12d8184f95e65

When comparing the data, `nsec` and `sig` part of `oracle.deleteRRSet(deleteType, name, nsec, sig, proof)` are exactly identical to the ones between `ens-app` and test on `dnssec-oracle` but the `proof` we pass from 
`matoken.xyz	300	DNSKEY` is different.

I am guessing that the they are different because 
when my test passes `dnssec-oracle` , it is using the proof taken from rrset of DNSKEY from `matoken.xyz` which signed TXT record of `_ens.matoken.xyz`.

However, when I construct proof at `ens-app` , I pass rreset of DNSKEY from `matoken.xyz` which signed the NSEC3 of `_ens.matoken.xyz` hence the signature is changed.

Screenshot 2020-10-14 at 19 18 31

Can you advise what else I should try to continue the debugging?

**Comment by makoto** [comment]
FYI, @gnidan from Truffle team debugged the transaction and it is in fact failing at verifying signature.


```
Transaction halted with a RUNTIME ERROR.

There was no revert message.  This may be due to an in intentional halting expression, such as assert(), revert(), or require(), or could be due to an unintentional exception such as out-of-gas exceptions.
Please inspect your transaction parameters and contract code to determine the meaning of this error.

Stacktrace:
Error: Revert or exceptional halt
  at DNSSECImpl.validateSignedSet [address 0x5112bF55F8510eb602cB2EE6d28961908e3F336D] (DNSSECImpl.sol:1250:9)
  at DNSSECImpl.deleteRRSet [address 0x5112bF55F8510eb602cB2EE6d28961908e3F336D] (DNSSECImpl.sol:1107:27)
  at unknown function [address 0x5112bF55F8510eb602cB2EE6d28961908e3F336D] (DNSSECImpl.sol:1102:5)

Location of error:

DNSSECImpl.sol:

1248:      */
1249:     function validateSignedSet(bytes memory input, bytes memory sig, bytes memory proof) internal returns(bytes memory name, bytes memory rrs) {
1250:         require(validProof(input.readName(RRSIG_SIGNER_NAME), proof));
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^```

**Pull request closed without merging**
