### PR TITLE
[WIP] enhancement/evm_setTime

### PR DESCRIPTION
**Pull request by decanus**

### CODE REVIEW

**Comment by decanus** [comment]
EVM set time seems to still not be supported.

**Comment by Arachnid** [comment]
Looks like you need to include package-lock.json in your PR.

**Comment by decanus** [comment]
@Arachnid yeah, we also need to wait anyway. `evm_setTime` does not seem to be supported yet.

**Comment by decanus** [comment]
@Arachnid looks like the function is now implemented, still trying to fix a few issues

**Pull request closed without merging**
